### ISSUE TITLE
Install Helm chart stored locally

### ISSUE THREAD

**Issue by PeterSR** [seacrew/helm-compose#134]
I am not sure if I have missed it in the documentation, but is it possible to install Helm charts from a local folder instead of a repo?

**Comment by tuunit** [comment]
Indeed you are right it is currently not mentioned anywhere that it supports path based and oci based charts as well

**Comment by PeterSR** [comment]
Hi @tuunit - Thank you for the reply. And apologies for going with a "look before you leap" approach. I was researching what tools might fulfill my need and was just looking at the docs. 

Will give it a try and get back if I encounter any problems :)

**Comment by tuunit** [comment]
No worries :)
