### ISSUE TITLE
No arm release?

### ISSUE THREAD

**Issue by dberuben** [seacrew/helm-compose#6]

**Comment by tuunit** [comment]
Hi @dberuben,

we have arm for linux and macos. Do you need an arm release for windows?

**Comment by dberuben** [comment]
Hi @tuunit 

I did a `helm plugin install https://github.com/seacrew/helm-compose` and i had an error saying that arm package doesn't exist  ... then i realize that package was present in the release section

**Comment by tuunit** [comment]
Hi @dberuben,

can you reproduce the error and share it here? Which OS are you using? I would like to analyze the issue so helm Plugin install works as well.

**Comment by dberuben** [comment]
Yes sure

```
helm plugin install https://github.com/seacrew/helm-compose
No prebuild binary for macos-arm64.
Failed to install helm-compose
\tFor support, go to https://github.com/seacrew/helm-compose/helm-compose.
Error: plugin install hook for "compose" exited with error
```
packages are present 🤔 

```
(☸|lspay-trial-eu-west-1:datadog)➜  plugins ls -la
total 0
drwxr-xr-x   4 dberuben  staff  128 Aug 28 13:55 .
drwxr-xr-x   3 dberuben  staff   96 Oct 21  2022 ..
drwxr-xr-x  20 dberuben  staff  640 Aug 28 13:55 helm-compose
drwxr-xr-x  23 dberuben  staff  736 Oct 21  2022 helm-diff
(☸|lspay-trial-eu-west-1:datadog)➜  plugins pwd
/Users/dberuben/Library/helm/plugins
```
helm version
```
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}
```

MacOS 13.5

**Comment by tuunit** [comment]
Hi @dberuben,

I found the issue:
https://github.com/seacrew/helm-compose/commit/940c9229817b782c5f7493538bb9c247bb5f42b4

If you have the time please try to uninstall and install once more :)

As I currently don't have direct access to a Mac I would highly appreciate any other feedback you have and if you find a bug. Please feel free to raise a issue asap.

**Comment by dberuben** [comment]
Fixed 🚀 

```
(☸|lspay-trial-eu-west-1:datadog)➜  plugins helm plugin install https://github.com/seacrew/helm-compose
Downloading https://github.com/seacrew/helm-compose/releases/latest/download/helm-compose-macos-arm64.tgz
Preparing to install into /Users/dberuben/Library/helm/plugins/helm-compose
helm-compose installed into /Users/dberuben/Library/helm/plugins/helm-compose
Installed plugin: compose
```
